main:
  ref/new/act zmp:
    legends:
      - { key: st_originRefZmp, id: [0-1] }
      - { key: st_originNewZmp, id: [0-1] }
      - { key: st_originActZmp, id: [0-1] }

  ref/act force:
    legends:
      - { key: rmfo_off_rfsensor, id: [2] }
      - { key: st_ref_rfsensor, id: [2] }
      - { key: rmfo_off_lfsensor, id: [2] }
      - { key: st_ref_lfsensor, id: [2] }

