extend:
  ../../common_plot.yaml

sh_qOut:
  func: plot_rad2deg
  data:
    - { log: sh_qOut, column: [0-33] }
es_q:
  func: plot_rad2deg
  data:
    - { log: es_q, column: [0-33] }
abc_q:
  func: plot_rad2deg
  data:
    - { log: abc_q, column: [0-33] }

abc_qAbc:
  func: plot_rad2deg
  data:
    - { log: abc_qAbc, column: [0-33] }

st_q:
  func: plot_rad2deg
  data:
    - { log: st_q, column: [0-33] }

RobotHardware0_q:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_q, column: [0-33] }

rh_st_diff:
  func: plot_rh_q_st_q
  data:
    - { log: RobotHardware0_q, column: [0-33] }
    - { log: st_q, column: [0-33] }

abs_enc_diff:
  func: plot_abs_enc
  data:
    - { log: RobotHardware0_servoState, column: [0-33] }
    - { log: RobotHardware0_servoState, column: [0-33] }

rmfo_off_rfsensor:
  func:
    plot_inverse
  data:
    - { log: rmfo_off_rfsensor, column: [0-5] }

rmfo_off_lfsensor:
  func:
    plot_inverse
  data:
    - { log: rmfo_off_lfsensor, column: [0-5] }

rmfo_off_rhsensor:
  data:
    - { log: rmfo_off_rhsensor, column: [0-5] }

rmfo_off_lhsensor:
  data:
    - { log: rmfo_off_lhsensor, column: [0-5] }

rfu_ref_rhsensorOut:
  data:
    - { log: rfu_ref_rhsensorOut, column: [0-5] }

rfu_ref_lhsensorOut:
  data:
    - { log: rfu_ref_lhsensorOut, column: [0-5] }

rfu_ref_rfsensorOut:
  data:
    - { log: rfu_ref_rfsensorOut, column: [0-5] }

rfu_ref_lfsensorOut:
  data:
    - { log: rfu_ref_lfsensorOut, column: [0-5] }

current:
  func: plot_current
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

imu_gsensor:
  data:
    - { log: RobotHardware0_gsensor, column: [0,1,2] }

imu_gyrometer:
  data:
    - { log: RobotHardware0_gyrometer, column: [0,1,2] }

rleg_motor_temp:
  func: plot_motor_temp
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

lleg_motor_temp:
  func: plot_motor_temp
  data:
    - { log: RobotHardware0_servoState, column: [6,7,8,9,10,11] }

motor_temp:
  func: plot_motor_temp
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

motor_outer_temp:
  func: plot_motor_outer_temp
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

comp:
  func: plot_comp
  data:
    -  { log: st_allEEComp, column: [0-11] }

watt:
  func: plot_watt
  data:
    - { log: RobotHardware0_dq, column: [0-11]  }
    - { log: RobotHardware0_tau, column: [0-11] }
torque:
  data:
    - { log: RobotHardware0_tau, column: [0,1,2,3,4,5,6,7,8,9,10,11] }
ServoState:
  func: plot_servostate
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }
abc_rfsensor:
  data:
    - { log: abc_rfsensor, column: [0,1,2,3,4,5] }
abc_lfsensor:
  data:
    - { log: abc_lfsensor, column: [0,1,2,3,4,5] }
12V:
  func: plot_12V
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

80V:
  func: plot_80V
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

st_zmp:
  data:
    - { log: st_zmp, column: [0,1] }

st_tmpCogValues:
  data:
    - { log: st_tmpCogValues, column: [0,1,2,3,4,5,6,7,8,9,10,11] }
