## cog
abc_cogOut:
  data:
    - { log: abc_cogOut, column: [0-2] }
abc_cogOut_with_offset:
  func: plot_with_offset
  data:
    - { log: abc_cogOut, column: [0-2] }
st_originActCog:
  data:
    - { log: st_originActCog, column: [0-2] }
st_originRefCog:
  data:
    - { log: st_originRefCog, column: [0-2] }
## cog velocity
st_originActCogVel:
  data:
    - { log: st_originActCogVel, column: [0-2] }
st_originRefCogVel:
  data:
    - { log: st_originRefCogVel, column: [0-2] }
## zmp
abc_zmpOut:
  data:
    - { log: abc_zmpOut, column: [0-2] }
abc_refZmp:
  data:
    - { log: abc_refZmp, column: [0-2] }
st_originActZmp:
  data:
    - { log: st_originActZmp, column: [0-2] }
st_originRefZmp:
  data:
    - { log: st_originRefZmp, column: [0-2] }
st_originNewZmp:
  data:
    - { log: st_originNewZmp, column: [0-2] }
abs_refzmp:
  func: plot_add
  data:
    - { log: abc_baseTformOut, column: [0-2] }
    - { log: abc_zmpOut, column: [0-2] }
# root-link relative zmp
st_zmp:
  data:
    - { log: st_zmp, column: [0-2] }
## force
sh_rfsensorOut:
  data:
    - { log: sh_rfsensorOut, column: [0-5] }
sh_lfsensorOut:
  data:
    - { log: sh_lfsensorOut, column: [0-5] }
sh_rhsensorOut:
  data:
    - { log: sh_rhsensorOut, column: [0-5] }
sh_lhsensorOut:
  data:
    - { log: sh_lhsensorOut, column: [0-5] }
RobotHardware0_rfsensor:
  data:
    - { log: RobotHardware0_rfsensor, column: [0-5] }
RobotHardware0_lfsensor:
  data:
    - { log: RobotHardware0_lfsensor, column: [0-5] }
RobotHardware0_rhsensor:
  data:
    - { log: RobotHardware0_rhsensor, column: [0-5] }
RobotHardware0_lhsensor:
  data:
    - { log: RobotHardware0_lhsensor, column: [0-5] }
rmfo_off_rfsensor:
  data:
    - { log: rmfo_off_rfsensor, column: [0-5] }
rmfo_off_lfsensor:
  data:
    - { log: rmfo_off_lfsensor, column: [0-5] }
rmfo_off_rhsensor:
  data:
    - { log: rmfo_off_rhsensor, column: [0-5] }
rmfo_off_lhsensor:
  data:
    - { log: rmfo_off_lhsensor, column: [0-5] }
st_ref_rfsensor:
  data:
    - { log: st_allRefWrench, column: [0-5] }
st_ref_lfsensor:
  data:
    - { log: st_allRefWrench, column: [6-11] }
st_ref_rhsensor:
  data:
    - { log: st_allRefWrench, column: [12-17] }
st_ref_lhsensor:
  data:
    - { log: st_allRefWrench, column: [18-23] }
# imu
imu_gsensor:
  data:
    - { log: RobotHardware0_gsensor, column: [0-2] }
imu_gyrometer:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_gyrometer, column: [0-2] }
# rpy
sh_baseRpyOut:
  func: plot_rad2deg
  data:
    - { log: sh_baseRpyOut, column: [0-2] }
st_actBaseRpy:
  func: plot_rad2deg
  data:
    - { log: st_actBaseRpy, column: [0-2] }
st_currentBaseRpy:
  func: plot_rad2deg
  data:
    - { log: st_currentBaseRpy, column: [0-2] }
kf_rpy:
  func: plot_rad2deg
  data:
    - { log: kf_rpy, column: [0-2] }
# pos
abc_basePos:
  data:
    - { log: abc_baseTformOut, column: [0-2] }
st_currentBasePos:
  data:
    - { log: st_currentBasePos, column: [0-2] }
# optional data
abc_contactStates:
  data:
    - { log: abc_contactStates, column: [0-3] }
abc_controlSwingSupportTime:
  data:
    - { log: abc_controlSwingSupportTime, column: [0-3] }
# time
time:
  func: plot_time
  data:
    - { log: sh_qOut, column: [0]}
# cp
st_ActCp:
  func: plot_cp
  data:
    - { log: st_originActCog, column: [0-1] }
    - { log: st_originActCog, column: [2,2] }
    - { log: st_originActCogVel, column: [0-1] }
st_RefCp:
  func: plot_cp
  data:
    - { log: st_originRefCog, column: [0-1] }
    - { log: st_originRefCog, column: [2,2] }
    - { log: st_originRefCogVel, column: [0-1] }
# diff
cog_diff:
  func: plot_diff
  data:
    - { log: st_originActCog, column: [0-2] }
    - { log: st_originRefCog, column: [0-2] }
zmp_diff:
  func: plot_diff
  data:
    - { log: st_originActZmp, column: [0-2] }
    - { log: st_originRefZmp, column: [0-2] }
cp_diff:
  func: plot_cp_diff
  data:
    - { log: st_originActCog, column: [0-1] }
    - { log: st_originActCog, column: [2,2] }
    - { log: st_originActCogVel, column: [0-1] }
    - { log: st_originRefCog, column: [0-1] }
    - { log: st_originRefCog, column: [2,2] }
    - { log: st_originRefCogVel, column: [0-1] }
# ee pos
eePosX:
  data:
    - { log: eePosX, column: [0-3] }
eePosY:
  data:
    - { log: eePosY, column: [0-3] }
# sbp
cog_with_sbp_x:
  func: plot_cog_with_sbp
  data:
    - { log: abc_cogOut, column: [0] }
    - { log: eePosX, column: [0]}
    - { log: eePosX, column: [1]}
    - { log: rfu_ref_rfsensorOut, column: [2] }
    - { log: rfu_ref_lfsensorOut, column: [2] }

cog_with_sbp_y:
  func: plot_cog_with_sbp
  data:
    - { log: abc_cogOut, column: [1] }
    - { log: eePosY, column: [0]}
    - { log: eePosY, column: [1]}
    - { log: rfu_ref_rfsensorOut, column: [2] }
    - { log: rfu_ref_lfsensorOut, column: [2] }

sbp_cog_offset_x:
  func: plot_sbp_cog_offset
  data:
    - { log: abc_cogOut, column: [0] }
    - { log: eePosX, column: [0]}
    - { log: eePosX, column: [1]}
    - { log: rfu_ref_rfsensorOut, column: [2] }
    - { log: rfu_ref_lfsensorOut, column: [2] }

sbp_cog_offset_y:
  func: plot_sbp_cog_offset
  data:
    - { log: abc_cogOut, column: [1] }
    - { log: eePosY, column: [0]}
    - { log: eePosY, column: [1]}
    - { log: rfu_ref_rfsensorOut, column: [2] }
    - { log: rfu_ref_lfsensorOut, column: [2] }

# rleg_current:
#   data:
#     - { log: rleg_current, column: [0-5] }

# lleg_current:
#   data:
#     - { log: lleg_current, column: [0-5] }

tmp:
  data:
    - { log: abc_tmp, column: [0-5] }
