extend:
  ../../common_plot.yaml

sh_qOut:
#  func: plot_rad2deg
  data:
    - { log: sh_qOut, column: [0-50] }

abc_q:
  func: plot_rad2deg
  data:
    - { log: abc_q, column: [0-50] }

st_q:
  func: plot_rad2deg
  data:
    - { log: st_q, column: [0-50] }

RobotHardware0_q:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_q, column: [0-50] }

RobotHardware0_q_lin:
  data:
    - { log: RobotHardware0_q, column: [0-50] }
RobotHardware0_dq_lin:
  data:
    - { log: RobotHardware0_dq, column: [0-50] }

RobotHardware0_tau:
  data:
    - { log: RobotHardware0_tau, column: [0-50] }

RobotHardware0_current:
  func: plot_current
  data:
    - { log: RobotHardware0_servoState, column: [0-50] }

atc_q:
  data:
    - { log: atc_q, column: [0-50] }

cta_q:
#  func: plot_rad2deg
  data:
    - { log: cta_q, column: [0-50] }

el_q:
#  func: plot_rad2deg
  data:
    - { log: el_q, column: [0-50] }

cta_tau:
  data:
    - { log: cta_tau, column: [0-50] }

vs_vrhsensor:
  data:
    - { log: vs_vrhsensor, column: [0-5] }

vs_vlhsensor:
  data:
    - { log: vs_vlhsensor, column: [0-5] }

rh_st_diff:
  func: plot_rh_q_st_q
  data:
    - { log: RobotHardware0_q, column: [0-50] }
    - { log: st_q, column: [0-50] }
cyl_diff:
  func: plot_rh_q_st_q
  data:
    - { log: RobotHardware0_q, column: [0-50] }
    - { log: atc_q, column: [0-50] }

abs_enc_diff:
  func: plot_abs_enc
  data:
    - { log: RobotHardware0_servoState, column: [0-50] }
    - { log: RobotHardware0_servoState, column: [0-50] }

rmfo_off_rfsensor:
  data:
    - { log: rmfo_off_rfsensor, column: [0-5] }

rmfo_off_lfsensor:
  data:
    - { log: rmfo_off_lfsensor, column: [0-5] }

rmfo_off_rhsensor:
  data:
    - { log: rmfo_off_rhsensor, column: [0-5] }

rmfo_off_lhsensor:
  data:
    - { log: rmfo_off_lhsensor, column: [0-5] }

rfu_ref_rhsensorOut:
  data:
    - { log: rfu_ref_rhsensorOut, column: [0-5] }

rfu_ref_lhsensorOut:
  data:
    - { log: rfu_ref_lhsensorOut, column: [0-5] }

current:
  func: plot_current
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

imu_gsensor:
  data:
    - { log: RobotHardware0_gsensor, column: [0,1,2] }

imu_gyrometer:
  data:
    - { log: RobotHardware0_gyrometer, column: [0,1,2] }

motor_temp:
  func: plot_motor_temp
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

motor_outer_temp:
  func: plot_motor_outer_temp
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

comp:
  func: plot_comp
  data:
    -  { log: st_allEEComp, column: [0, 1, 2, 3, 4, 5] }

watt:
  func: plot_watt
  data:
    - { log: RobotHardware0_dq, column: [0,1,2,3,4,5]  }
    - { log: RobotHardware0_tau, column: [0,1,2,3,4,5] }

ServoState:
  func: plot_servostate
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

12V:
  func: plot_12V
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

80V:
  func: plot_80V
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

st_zmp:
  data:
    - { log: st_zmp, column: [0,1] }

